config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  resource :registrations, only: %i[new create]
  resource :sessions, only: %i[new create destroy]

  resources :accounts
  resources :transactions
  resources :budgets
end

app/models/transactions/expense.rb
# frozen_string_literal: true

module Transactions
  class Expense < Transaction
    belongs_to :category

    alias_attribute :account, :source_account

    scope :by_budget, ->(budget) { where(category: budget.category) }
  end
end

app/models/transactions/income.rb
# frozen_string_literal: true

module Transactions
  class Income < Transaction
    belongs_to :category

    alias_attribute :account, :destination_account
  end
end

app/models/transactions/transfer.rb
# frozen_string_literal: true

module Transactions
  class Transfer < Transaction
    def category
      nil
    end
  end
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_transaction, only: %i[edit update destroy]
  before_action :load_categories, :load_user_accounts, only: %i[new create update edit]

  def index
    @transactions = ListTransactions.new(
      user_id: current_user.id,
      page: params.fetch(:page, 1),
      category_id: params[:category_id]
    ).call
  end

  def new
    @transaction = Transaction.new
  end

  def edit; end

  def create
    @transaction = CreateTransaction.new(user_id: current_user.id, **transaction_params).call

    if @transaction.persisted?
      redirect_to transactions_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @transaction = UpdateTransaction.new(transaction: @transaction, **transaction_params).call

    if @transaction.valid?
      redirect_to transactions_path
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    DeleteTransaction.new(transaction: @transaction).call
  end

  private

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  def load_categories
    @categories = Category.all
  end

  def load_user_accounts
    @accounts = current_user.accounts
  end

  def transaction_params
    params.require(:transaction).permit(
      :amount, :description, :source_account_id, :destination_account_id, :type, :category_id
    ).to_h.deep_symbolize_keys
  end
end

app/views/transactions/_form.html.erb
<%= form_with model: @transaction.becomes(Transaction), local: true, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4", data: { controller: 'transactions' } do |form| %>
    
    <% if @transaction.errors.any? %>
      <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mb-4">
        <strong class="font-bold">Oops!</strong>
        <span class="block sm:inline">There were some problems with your input:</span>
        <ul class="mt-2 list-disc list-inside text-sm text-red-600">
          <% @transaction.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-4">
      <%= form.label :amount, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.number_field :amount, step: :any, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
      <span class="block text-gray-700 text-sm font-bold mb-2">Transaction Type</span>
      <div class="flex items-center">
        <%= form.radio_button :type, 'Transactions::Expense', class: "mr-2 leading-tight" %>
        <%= form.label :type_expense, 'Expense', class: "mr-4 text-gray-700" %>

        <%= form.radio_button :type, 'Transactions::Income', class: "mr-2 leading-tight" %>
        <%= form.label :type_income, 'Income', class: "mr-4 text-gray-700" %>

        <%= form.radio_button :type, 'Transactions::Transfer', class: "mr-2 leading-tight" %>
        <%= form.label :type_transfer, 'Transfer', class: "mr-4 text-gray-700" %>
      </div>
    </div>

    <div class="mb-4">
      <%= form.label :source_account_id, "Source Account", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.collection_select :source_account_id, @accounts, :id, :name, prompt: 'Select Source Account', class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
      <%= form.label :destination_account_id, "Destination Account", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.collection_select :destination_account_id, @accounts, :id, :name, prompt: 'Select Destination Account', class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-4">
      <%= form.label :category_id, "Category", class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.collection_select :category_id, @categories, :id, :name, prompt: 'Select Category', class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="mb-6">
      <%= form.label :description, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= form.text_area :description, rows: 3, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>

    <div class="flex items-center justify-between">
      <%= form.submit class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    </div>

  <% end %>

app/views/transactions/edit.html.erb
<div class="max-w-md mx-auto mt-10">
  <h1 class="text-2xl font-bold mb-5 text-center">Edit Transaction</h1>
  <div class="my-2">
    <%= link_to 'All Transactions', transactions_path%>
  </div>
  
  <%= render "form" %>
</div>

app/views/transactions/index.html.erb
<div class="max-w-3xl mx-auto mt-10">
  <h1 class="text-2xl font-bold mb-5 text-center">Your Transactions</h1>

  <% if @transactions.any? %>
    <table class="min-w-full bg-white shadow-md rounded">
      <thead>
        <tr>
          
          <th class="py-2 px-4 bg-gray-200 border-b">ID</th>
          <th class="py-2 px-4 bg-gray-200 border-b">Transaction Type</th>
          <th class="py-2 px-4 bg-gray-200 border-b">Account</th>
          <th class="py-2 px-4 bg-gray-200 border-b">Amount</th>
          <th class="py-2 px-4 bg-gray-200 border-b">Category</th>
          <th class="py-2 px-4 bg-gray-200 border-b">Date</th>
          <th class="py-2 px-4 bg-gray-200 border-b">Actions</th>
        </tr>
      </thead>
      <tbody>
        <% @transactions.each do |transaction| %>
          <tr>
            <td class="py-2 px-4 border-b"><%= transaction.id %></td>
            <td class="py-2 px-4 border-b capitalize"><%= transaction.type %></td>
            <td class="py-2 px-4 border-b"><%= transaction.account_name %></td>
            <td class="py-2 px-4 border-b"><%= number_with_delimiter(transaction.amount) %></td>
            <td class="py-2 px-4 border-b"><%= transaction.category&.name %></td>
            <td class="py-2 px-4 border-b"><%= transaction.created_at.strftime("%Y-%m-%d") %></td>
            <td class="py-2 px-4 border-b" data-turbo-prefetch="false">
              <%= link_to 'Edit', edit_transaction_path(transaction), class: "inline-block bg-yellow-300 hover:bg-yellow-400 text-yellow-900 font-bold py-1 px-2 rounded mr-2" %>
              <%= link_to 'Delete', transaction_path(transaction), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class: "inline-block bg-red-500 hover:bg-red-700 text-white font-bold py-1 px-2 rounded" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p class="text-center text-gray-600 mt-5">You have no accounts. <%= link_to 'Create one', new_account_path, class: "text-blue-500 underline" %></p>
  <% end %>
</div>

app/views/transactions/new.html.erb
<div class="max-w-md mx-auto mt-10">
  <h1 class="text-2xl font-bold mb-5 text-center">Create Transaction</h1>

  <div class="my-2">
    <%= link_to 'All Transactions', transactions_path%>
  </div>
  <%= render "form" %>
</div>