config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'home#index'

  resource :registrations, only: %i[new create]
  resource :sessions, only: %i[new create destroy]

  resources :accounts
  resources :transactions
  resources :budgets
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expense Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

   <body class="bg-gray-100 h-screen antialiased leading-none">

    <header class="bg-blue-500 text-white shadow">
      <div class="container mx-auto flex justify-between items-center px-6 py-3">
        <div>
          <a href="/" class="font-bold text-lg">
            Expense Management
          </a>
        </div>
        <nav class="space-x-4 text-sm sm:text-base">
          <%= link_to 'New Transaction', new_transaction_path, class: "no-underline hover:underline"%>
          <%= link_to 'Add Account', new_account_path, class: "no-underline hover:underline"%>
          <%= link_to 'View Accounts', accounts_path, class: "no-underline hover:underline"%>
          <%= link_to 'View Transactions', transactions_path, class: "no-underline hover:underline"%>
          <%= link_to 'Create Budget', new_budget_path, class: "no-underline hover:underline"%>
          <%= link_to 'View Budgets', budgets_path, class: "no-underline hover:underline"%>
          <%= link_to 'Logout', sessions_path, data: { turbo_method: :delete}, class: "no-underline hover:underline" %>
        </nav>
      </div>
    </header>

    <main class="container mx-auto mt-10">
      <%= yield %>
    </main>
    
    <footer class="bg-blue-500 text-white text-center py-4">
      &copy; 2023 Your Company
    </footer>
  </body>
</html>

app/views/layouts/basic.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Expense Management</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>